### PR TITLE
:sparkles: Arbitrary pose derivatives & bugfixes

### PR DESCRIPTION
**Pull request by jmakif**
Refactors `Pose` to be an abstract class allowing for arbitrary time derivatives. In doing so, also makes the template header only again. Additionally, fix issues with `+` or `-` operators between a named quantity type (IE the `Length` class) and the equivalent `Quantity` failing, while at the same time improving error messages when using mismatched types in either of those operations.

### CODE REVIEW

**Comment by madelyn-sz** [comment]
Everything looks good code wise. 

I'm not totally sure that `static_assert`s are the right way to handle binary operators not working with the nominal types though. It would require all the asserts to be in every operator defined outside of `Quantity` (not just `+` and `-`), and I'm a bit worried it might screw up overloading since static asserts do not prevent a template from being selected during overload resolution.

Pose derivatives look all good.

**Review by liam-teale — APPROVED** [review]
LGTM

**Comment by madelyn-sz** [comment]
OK so some bad news and some good news:

The bad news: This problem applies to more than just operators. It actually applied to any function which takes >1 quantity values of the same type (eg.min, max, ceil, floor, round, mod)

The good news: The issue lies in the fact that the a single type parameter is used for the function parameters. Template instantiation requires types to be strictly equal, not just convertible, and so no implicit conversion can happen. 

This is pretty easy to solve: We take a different quantity type for each parameter. This fixes the issue, but allows these functions to be instantiated with all different quantity types. This still errors, but not as nicely, as the template must be instantiated first. I think the best course of action here is to create some kind of type convertible trait/concept to restrict the parameters. 
This would allow the operators to work between isomorphic quantity types instead of erroring out

```c++
template<typename Q, typename... Quantities>
concept Isomorphic = ((std::convertible_to<Q, Quantities> && std::convertible_to<Quantities, Q>) && ...);
```

**Review by madelyn-sz — APPROVED** [review]
Looks all good to me!

**Pull request merged**
